### ISSUE TITLE
Hangs on loss of internet connection

### ISSUE THREAD

**Issue by jonnym1** [rany2/grott#1]
Hi,

When in forwarding mode to growatt servers, grott will hang if the internet connection to the outside world is lost and stops sending MQTT data over local network and also drops local connection to Shine dongle.
Restarting the grott server while the internet is down causes it to hang and never startup. 
I'm guessing, never tested, that if the growatt servers were to ever go down the same thing would happen?

**Comment by rany2** [comment]
Is this in grottserver mode?

**Comment by jonnym1** [comment]
Yes, server mode, the server is running locally but forwarding a copy of the data to growatt's servers.

**Comment by rany2** [comment]
Alright I believe I could resolve this issue, I found the culprit

**Comment by jonnym1** [comment]
Also the same issue with the pvoutput.org function but this is easily solved by changing the following in grottdata.py
      reqret = requests.post(conf.pvurl, data = pvdata2, headers = pvheader)
add a timeout
      reqret = requests.post(conf.pvurl, data = pvdata2, headers = pvheader, timeout=2.50)

all 3 times requests.post is used

**Comment by rany2** [comment]
Could you test it out now?

**Comment by jonnym1** [comment]
Had to change the following to get working with serverforward disabled..

`reqret = requests.post(conf.pvurl, data=pvdata, headers=pvheader, timeout=conf.forwardsocketimeout,)`

to
```
                try:
                    reqret = requests.post(conf.pvurl, data=pvdata, headers=pvheader, timeout=conf.forwardsocketimeout,)
                except:
                    print("\t\t -  PV Out conn error")
```


However with serverforward enabled it just hangs on startup...

```
Grott Growatt logging monitor : 2.7.4

Grott process configuration file

Grott process environmental variables

Grott override settings if set in commandline

Grott process json layout files
t06NNNNXSPH.json
         - GrottHttpserver - Ready to listen at: 0.0.0.0:5782
         - GrowattServer - Ready to listen at: 0.0.0.0:5279
         - Grottserver - Client connected: ('192.168.1.42', 29603)
         - Start server forward

```

**Comment by rany2** [comment]
Nowhere do I have "- Start server forward" in the code. Maybe you have some of your own changes still?

**Comment by jonnym1** [comment]
I put that in for debugging, inserted above 
817             forward = Forward().start(host, port)

re-downloaded new copy of grottserver.py and hangs on...
```
         - GrottHttpserver - Ready to listen at: 0.0.0.0:5782
         - GrowattServer - Ready to listen at: 0.0.0.0:5279
         - Grottserver - Client connected: ('192.168.1.42', 22039)
```
Turn internet connection back on and all fine...

```
         - GrottHttpserver - Ready to listen at: 0.0.0.0:5782
         - GrowattServer - Ready to listen at: 0.0.0.0:5279
         - Grottserver - Client connected: ('192.168.1.42', 10058)
         - Grott MQTT topic used : energy/growatt
         - Grott MQTT topic used : energy/growatt
```

**Comment by rany2** [comment]
I'm going to revert my MQTT changes but you could always add these yourself. I'm going to spin up a dedicated thread for forwarding now. I think it should work then

**Comment by rany2** [comment]
Try now

**Comment by jonnym1** [comment]
Interestingly, If the internet connection drops while grott is running its carrys on working fine, Its only when starting up that it hangs now! Just don't restart grott while the internet is down... I can live with that.

I think in unique in my thinking, I want everything in house to be able to function independently and not be reliant on other peoples servers or the internet working.

**Comment by jonnym1** [comment]
Ok will try the latest changes now...

**Comment by rany2** [comment]
Just keep in mind latest changes have all my MQTT stuff reverted. You'll need to add the timeout stuff yourself

**Comment by rany2** [comment]
If you want you could try to make it polished for MQTT timeout, I don't have MQTT myself (only Influx) so I can't test it out

**Comment by rany2** [comment]
Made a few more changes, can you please test out the current version now?

**Comment by jonnym1** [comment]
It seems pretty much unbreakable now, good work!!

Typo here...         
```
        forward = Forward(conf.forwardsocketimeout).start(self.forward_to[0], self.forward_to[1])
        forward = Forward(conf.forwardsockettimeout).start(self.forward_to[0], self.forward_to[1])
```

**Comment by rany2** [comment]
@jonnym1 I think I've already fixed that, you're probably checking an older version.

**Comment by rany2** [comment]
But anyway this is good news, I guess this could be closed now

**Comment by jonnym1** [comment]
Thanks for all your hard work!

**Comment by rany2** [comment]
BTW I've commited https://github.com/rany2/grott/commit/72157c136c6d5ef2e667a14e14f3aa1e714d6474 for PVOutput timeout. I can't do anything about MQTT because of https://github.com/eclipse/paho.mqtt.python/issues/353 unfortunately.

I also switched InfluxDB to use the async write option so it shouldn't hang in these situations. https://github.com/rany2/grott/commit/d28b6241162dad26a8b5e805817459db7ccb8ac2

The only issue write now is MQTT then, but please confirm all is fine. I don't use PVOutput so I can't know.

**Comment by rany2** [comment]
Something I guess I could do is pushing MQTT data to it's own process using mp and then killing it when the time runs out, but that's not really ideal. The solutions in that GH issue aren't any good either and wouldn't work well for us.
