### ISSUE TITLE
[Feature Request] Add simple Web UI to set / get register values to grottserver

### ISSUE THREAD

**Issue by hugoboss00** [rany2/grott#27]
I would be more convenient to have a Web UI to set/get register values from inverter/datalogger.
It would be needed mostly for grottserver, because here the Growatt Web Portal cannot be used to set/get registers.

**Comment by rany2** [comment]
This shouldn't be too difficult. I'll work on it when I have the time :)

**Comment by rany2** [comment]
WIP: 

![image](https://user-images.githubusercontent.com/71077389/219964356-981f0b7c-9fa8-4199-a597-c8c5d38bd785.png)

**Comment by rany2** [comment]
WIP:

![image](https://user-images.githubusercontent.com/71077389/219964830-d29ed737-a746-4ca7-9786-1a1e8e5a183e.png)

**Comment by rany2** [comment]
P.S. if you're good with web development, please fix the terrible UI... but it is sort of functional :P

**Comment by rany2** [comment]
Implemented, let me know how it goes!

**Comment by rany2** [comment]
Looks fancier now:

![image](https://user-images.githubusercontent.com/71077389/219973841-7d0107b3-a8b8-4a45-9884-7b3dcdf798bb.png)

**Comment by rany2** [comment]
![image](https://user-images.githubusercontent.com/71077389/219973877-f2c9422a-5422-495d-9f6d-9be3b04d2a2e.png)

There's a light theme too, but it only switches themes based on your system's theme.

**Comment by hugoboss00** [comment]
Hi, i just tried it out, and it worked very well.
Thank you very much, this is a big convenience improvement!

**Comment by rany2** [comment]
Thank you @hugoboss00 , glad to hear!
