### ISSUE TITLE
Grott not connecting to MQTT?

### ISSUE THREAD

**Issue by xhemp** [rany2/grott#30]
Greetings,

Very nice fork from the original Grott, great job on this!
I am trying to move from the original Grott to your fork (because of the API/logging and the fact that you still forward to Growatt in this mode) but it looks like i can't see MQTT connecting so I am at a loss on what could be gone wrong.
Does MQTT work on server mode? What about the grott_ha extension?
I can't see Grott connecting to my MQTT server when using your fork and just wondering what could be happening.
The nomqtt is set to false and as far as I can see, there's nothing preventing Grott to connect.

Many thanks!

**Comment by rany2** [comment]
@xhemp Hello, it should in fact work in server mode. Could you share any output in debug mode?

**Comment by xhemp** [comment]
Hello, thanks for getting back to me!
No worries, It's fine!
Here's the URL:

https://ctxt.io/2/AACQGo73FA

I seet debug = true and mincrecl = 100, any other way to get more info I can try?

**Comment by rany2** [comment]
@xhemp Does this occur only for server mode?

**Comment by xhemp** [comment]
> @xhemp Does this occur only for server mode?

I didn't test that before but just ran it in proxy mode and it still doesn't connect to MQTT.
This is what I have in my config but I can't even see the client connecting:

nomqtt = False
ip = localhost
port = 1883
topic= energy/growatt
auth = False

**Comment by rany2** [comment]
Are you sure it works on Johan's version?On 13 Mar 2023 11:37 AM, xhemp ***@***.***> wrote:

@xhemp Does this occur only for server mode?

I didn't test that before but just ran it in proxy mode and it still doesn't connect to MQTT.
This is what I have in my config but I can't even see the client connecting:
nomqtt = False
ip = localhost
port = 1883
topic= energy/growatt
auth = False

**Comment by xhemp** [comment]
> Are you sure it works on Johan's version?On 13 Mar 2023 11:37 AM, xhemp ***@***.***> wrote: @xhemp Does this occur only for server mode? I didn't test that before but just ran it in proxy mode and it still doesn't connect to MQTT. This is what I have in my config but I can't even see the client connecting: nomqtt = False ip = localhost port = 1883 topic= energy/growatt auth = False —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

It does, yes, I am running it at this right moment and I can see the topic created and being updated.

**Comment by xhemp** [comment]
Just thinking here, my inverter type is SPA, does your fork use the latest beta? or ish? :)

**Comment by rany2** [comment]
@xhemp It should be on the latest. When running in server mode, do you at least see that grott is processing records?

**Comment by xhemp** [comment]
Yes, it looks like it is but I am not sure if it's processing SPA's data as it should, though:

`Mar 14 20:12:18 host grott[2133080]: - Grott automatic protocol detection
Mar 14 20:12:18 host grott[2133080]: - Grott data record length 839
Mar 14 20:12:18 host grott[2133080]: - layout   :  T060104XSPA
Mar 14 20:12:18 host grott[2133080]: - no matching record layout found, try generic
Mar 14 20:12:18 host grott[2133080]: - no matching record layout found, standard processing performed
Mar 14 20:12:18 host grott[2133080]: - Record layout used: none
Mar 14 20:12:18 host grott[2133080]: - Grott Growatt data decrypted
Mar 14 20:12:18 host grott[2133080]: - Growatt plain data:
Mar 14 20:12:18 host grott[2133080]:         001d0006033f01044a504338434c36314b360000000000000000000000000000000000000000575
Mar 14 20:12:18 host grott[2133080]:         04441434636303439000000000000000000000000000000000000000017030e140c110303e80464
Mar 14 20:12:18 host grott[2133080]:         00060000000000000000000000000000000000000e1000000000020b003b0000000000000000000
Mar 14 20:12:18 host grott[2133080]:         00000000000000000000000000000000000000000000000000e74000000000000000000000e7400
Mar 14 20:12:18 host grott[2133080]:         0000b400060b8d28b4000000080000024d000000010000005c00000023000001680000003400000
Mar 14 20:12:18 host grott[2133080]:         1d00000004c00000461000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000003e80000006300000000003b146efd4e0011258a1bf82f1286860005000700641630000
Mar 14 20:12:18 host grott[2133080]:         00000000086860000000000004150415000000cc70cc300010e100cc50cc50cc60cc50cc50cc50c
Mar 14 20:12:18 host grott[2133080]:         c50cc60cc60cc70cc60cc70000046504e10038000001f90000000003cc000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         000000000470000031000000046000002b700000e7400000e100000000000010000016400010000
Mar 14 20:12:18 host grott[2133080]:         01cc000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000010cc70cc200010010000e000100cc009e000300010000003b003b000000000
Mar 14 20:12:18 host grott[2133080]:         0000000002300c00041000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         00000000000000000000000000000000000000000000000000000000000007d0084c00060000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000c99138909b3000d00000cdc0
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000220000017c001e1e98000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         00000000000000000000000000000000000000000000000d700c200c80000020a0f930f94000000
Mar 14 20:12:18 host grott[2133080]:         000000007100000056000002d8000000470000031000000038000001f9000000000000000100000
Mar 14 20:12:18 host grott[2133080]:         0000000000000009f0c
Mar 14 20:12:18 host grott[2133080]: - Grott data ack record or data record not defined no processing done
Mar 14 20:12:18 host grott[2133080]: - Grottserver - Plain record:
Mar 14 20:12:18 host grott[2133080]:         001d0006033f01044a504338434c36314b360000000000000000000000000000000000000000575
Mar 14 20:12:18 host grott[2133080]:         04441434636303439000000000000000000000000000000000000000017030e140c110303e80464
Mar 14 20:12:18 host grott[2133080]:         00060000000000000000000000000000000000000e1000000000020b003b0000000000000000000
Mar 14 20:12:18 host grott[2133080]:         00000000000000000000000000000000000000000000000000e74000000000000000000000e7400
Mar 14 20:12:18 host grott[2133080]:         0000b400060b8d28b4000000080000024d000000010000005c00000023000001680000003400000
Mar 14 20:12:18 host grott[2133080]:         1d00000004c00000461000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000003e80000006300000000003b146efd4e0011258a1bf82f1286860005000700641630000
Mar 14 20:12:18 host grott[2133080]:         00000000086860000000000004150415000000cc70cc300010e100cc50cc50cc60cc50cc50cc50c
Mar 14 20:12:18 host grott[2133080]:         c50cc60cc60cc70cc60cc70000046504e10038000001f90000000003cc000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         000000000470000031000000046000002b700000e7400000e100000000000010000016400010000
Mar 14 20:12:18 host grott[2133080]:         01cc000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000010cc70cc200010010000e000100cc009e000300010000003b003b000000000
Mar 14 20:12:18 host grott[2133080]:         0000000002300c00041000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         00000000000000000000000000000000000000000000000000000000000007d0084c00060000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000c99138909b3000d00000cdc0
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000220000017c001e1e98000000000000
Mar 14 20:12:18 host grott[2133080]:         0000000000000000000000000000000000000000000000000000000000000000000000000000000
Mar 14 20:12:18 host grott[2133080]:         00000000000000000000000000000000000000000000000d700c200c80000020a0f930f94000000
Mar 14 20:12:18 host grott[2133080]:         000000007100000056000002d8000000470000031000000038000001f9000000000000000100000
Mar 14 20:12:18 host grott[2133080]:         0000000000000009f0c
Mar 14 20:12:18 host grott[2133080]: - Grottserver - 0104 data record received
Mar 14 20:12:18 host grott[2133080]: - Grottserver - Response:
Mar 14 20:12:18 host grott[2133080]:         \x00\x1d\x00\x06\x00\x03\x01\x04\x47\x75\xd9- Grottserver - Sending forward data for 47.91.67.66:5279
Mar 14 20:12:18 host grott[2133080]: - Grottserver - Put response on queue:  - Grottserver - Forward data sent for 47.91.67.66:5279
Mar 14 20:12:18 host grott[2133080]: 192.168.2.202_19754  msg:
Mar 14 20:12:18 host grott[2133080]:         \x00\x1d\x00\x06\x00\x03\x01\x04\x47\x75\xd9`

host`

**Comment by rany2** [comment]
Could you please tell me your exact inverter type?

**Comment by xhemp** [comment]
Sure, I have a SPA3000 ( https://www.alternergy.co.uk/growatt-spa3000-ac-coupled )

**Comment by rany2** [comment]
@xhemp I believe I know the cause, but the fix will take some time unfortunately

**Comment by xhemp** [comment]
No worries, Rany, I am using Johan's for now. Thanks for looking into it.

**Comment by rany2** [comment]
@xhemp Could you please test it now?

**Comment by xhemp** [comment]
@rany2 Just pulled and tested but I don't believe MQTT is connecting as I can't see the topics being updated.
If there's anything I can do to further test, let me know!

**Comment by xhemp** [comment]
> @xhemp can you share your verbose log as well (but wait until the datalogger sends data)

Sure thing, here it is: https://ctxt.io/2/AACQUsstFQ

**Comment by rany2** [comment]
@xhemp This works with Johan's beta?

**Comment by xhemp** [comment]
> @xhemp This works with Johan's beta?

It does, yes, dont have any issues with MQTT.

**Comment by rany2** [comment]
@xhemp I can't seem to get it to work with Johan's version either https://paste.debian.net/1274136/

**Comment by xhemp** [comment]
I am using his latest beta (because of the SPA support) and I can see it populating my MQTT topics (using MQTT Explorer/ mqtt_sub), I don't see that happening when using your fork so I am at a loss now on what could be happening.

**Comment by rany2** [comment]
@xhemp That packet doesn't appear to be a data record anyway. I've just verified it. Could you verify that Johan's grottserver works? This might be a grottserver bug.

**Comment by rany2** [comment]
Another possibility is that you didn't reach the interval for the data record? By default the datalogger only sends a data recovery every 5minutes.

**Comment by xhemp** [comment]
> @xhemp That packet doesn't appear to be a data record anyway. I've just verified it. Could you verify that Johan's grottserver works? This might be a grottserver bug

I will triple check here.

> Another possibility is that you didn't reach the interval for the data record? By default the datalogger only sends a data record every 5minutes.

I set it to 1 minute.

**Comment by xhemp** [comment]
This is Johan's grottserver and grott's output: 

https://paste.debian.net/1274144/


192.168.2.165 is where I run grott and 192.168.2.202 is my inverter.
And this is my HA logbook (this is populated from MQTT ):

![ha](https://user-images.githubusercontent.com/13650956/225414031-c801c794-bcde-4b4a-a6a8-4aec1bedebbb.jpg)

**Comment by rany2** [comment]
@xhemp thanks, might be something with my grottserver? Could you confirm that my fork works with grottproxy? This way I could single out grottdata.

**Comment by xhemp** [comment]
No, doesn't work.
Looks like there's something missing on grottconf and maybe somewhere else?


This is on Johan's:

# grep T06NNNNXSPA *
grottconf.py:        self.recorddict13 = {"T06NNNNXSPA": {
grottconf.py:        self.recorddict.update(self.recorddict13)                   #T06NNNNXSPA

This is on yours:

$ grep T06NNNNXSPA *
$

**Comment by xhemp** [comment]
> @xhemp ah, I was comparing myself against Johan's 2.7 branch. That was very stupid.

It happens, too much happening at the same time :)
Looks like 2.8.1 is the one that brought SPA into the mix:

New in Version 2.8
    Added first SPA support (2.8.1)

**Comment by rany2** [comment]
Now it should work!

**Comment by xhemp** [comment]
Yes! This one works well I can see energy/growatt being populated so it works well!
There's an issue but it might not related to anything on your side, it can't load the HA script which looks like it loads on Johan's:

 Grott extension processing started:  grott_ha
 [Grott HA] 0.0.7-RC8 Can't configure device: WPDACFXXXX (this is my inverter serial) 

But it's quite good already, pretty happy that server mode works along with the Shine App/Web.

**Comment by rany2** [comment]
@xhemp Could you test the version in master now?

**Comment by xhemp** [comment]
> @xhemp Could you test the version in master now?

Just had to go out for a bit but will test it as soon as I'm back and report.

**Comment by xhemp** [comment]
Got the same as before:

- Grott extension processing started:  grott_ha
	[Grott HA] 0.0.7-RC8 Can't configure device: WPDACFXXXX

This is what i have on Johan's:

Grott HA 0.0.7-RC8 - creating WPDACF6049 config in HA, 130 to push
 Pushing 131 configurations payload to HA

**Comment by rany2** [comment]
@xhemp Could you try again?

**Comment by xhemp** [comment]
You rule, man, it's working now!

- Grott extension processing started:  grott_ha
	Grott HA 0.0.7-RC8 - creating WPDACF6049 config in HA, 130 to push
	Pushing 131 configurations payload to HA
	Configurations pushed

Again, thank you very much for the persistence on this and for creating this fork!

**Comment by rany2** [comment]
Perfecto! Glad to hear. Btw there is a web interface you could use to set inverter settings, you don't need to use the Growatt app.

**Comment by xhemp** [comment]
Yes, I've been playing with the settings on the SPA, the idea is to ditch the app/web and only use your fork and HA!
Thanks again.
