### ISSUE TITLE
TypeError("'Conf' object does not support item assignment")

### ISSUE THREAD

**Issue by Hemmahackaren** [rany2/grott#32]
Gave your fork a try as it would be a great improvement to combine grottserver with the ability to still have the Shinephone app working. Running in "server" mode

However I was not able to get the csv-plugin to work. Log (with some parts snipped):

`python3 grott.py -v

Grott Growatt logging monitor : 2.7.6

Grott Command line parameters processed:
        verbose:                 True
        config file:             grott.ini
        nomqtt:                  False
        inverterid:              automatic
        pvoutput:                False
        noipf:                   False

Grott process configuration file

Grott override settings if set in commandline

Grott process json layout files

Grott layout records loaded
<snip>

Grott settings:

_Generic:
        minrecl                         100
        verbose                         True
        includeall                      False
        invtype                         tl3
        invtypemap                      {}
        inverterid                      automatic
        noipf                           False
        time                            server
        sendbuf                         True
        timezone                        local
        mode                            proxy
        ip                              default
        port                            5279
        timeout                         300.0
_Growatt:
        ip                              47.91.67.66
        port                            5279
_Server:
        httpip                          0.0.0.0
        httpport                        5782
        httptoken                       **secret**
        httptimeout                     10.0
        registerreadtimeout             7.0
        registerwritetimeout            15.0
        firstping                       False
        sendseq                         1
        serverforward                   True
        forwardretry                    1
        forwardtimeout                  2.0
        write_delay_ms                  100
_MQTT:
        nomqtt                          True
        ip                              localhost
        port                            1883
        topic                           energy/growatt
        deviceidintopic                 False
        mtopic                          False
        mtopicname                      energy/meter
        retain                          False
        auth                            False
        user                            grott
        password                        **secret**
_PVOutput:
        pvoutput                        False
        pvtemp                          False
        pvdisv1                         False
        pvinverters                     1
        apikey                          **secret**
        pvuplimit                       5
        systemid1                       systemid1
        inverterid1                     inverter1
        systemid                        systemid1
        pvtimeout                       2.5
_influx:
        influx                          False
        url                             http://localhost:8086
        org                             grottorg
        bucket                          grottdb
        token                           **secret**
_extension:
        extension                       True
        extname                         grotcsv
        extvar                          {'outpath': '/home/martin/rany2grott/csv/'}

- Grottproxy - Ready to listen at: 0.0.0.0:5279
- Grottproxy - Client connected: ('192.168.1.235', 1719)

<snip>

- Grott server date/time used
- Grott values retrieved:
        -  datalogserial        :  <snip>
        -  pvserial             :  <snip>
        -  pvstatus             :  1
        -  pvpowerin            :  356.3
        -  pv1voltage           :  670.9
        -  pv1current           :  0.2
        -  pv1watt              :  134.1
        -  pv2voltage           :  435.3
        -  pv2current           :  0.2
        -  pv2watt              :  87.0
        -  pvpowerout           :  351.0
        -  pvfrequentie         :  50.0
        -  pvgridvoltage        :  229.4
        -  pvgridcurrent        :  0.7
        -  pvgridpower          :  160.5
        -  pvgridvoltage2       :  236.3
        -  pvgridcurrent2       :  0.7
        -  pvgridpower2         :  165.4
        -  pvgridvoltage3       :  230.1
        -  pvgridcurrent3       :  0.7
        -  pvgridpower3         :  161.0
        -  Vac_RS               :  394.3
        -  Vac_ST               :  409.5
        -  Vac_TR               :  401.1
        -  pvenergytoday        :  39.9
        -  pvenergytotal        :  4772.8
        -  totworktime          :  2054.7
        -  epv1today            :  22.2
        -  epv1total            :  2599.9
        -  epv2today            :  15.8
        -  epv2total            :  1850.9
        -  epvtotal             :  4450.8
        -  pvtemperature        :  59.6
        -  pvipmtemperature     :  33.2
        -  pvboottemperature    :  31.1
        -  uwBatVolt_DSP        :  0.0
        -  pbusvolt             :  3464
        -  nbusvolt             :  3482
- MQTT jsonmsg:
        {"device": "<snip>", "time": "2023-03-15T17:20:25", "buffered": "no",
        "values": {"datalogserial": "<snip>", "pvserial": "<snip>", "pvstatus":
        1, "pvpowerin": 3563, "pv1voltage": 6709, "pv1current": 2, "pv1watt": 1341,
        "pv2voltage": 4353, "pv2current": 2, "pv2watt": 870, "pvpowerout": 3510,
        "pvfrequentie": 5000, "pvgridvoltage": 2294, "pvgridcurrent": 7, "pvgridpower":
        1605, "pvgridvoltage2": 2363, "pvgridcurrent2": 7, "pvgridpower2": 1654,
        "pvgridvoltage3": 2301, "pvgridcurrent3": 7, "pvgridpower3": 1610, "Vac_RS":
        3943, "Vac_ST": 4095, "Vac_TR": 4011, "pvenergytoday": 399, "pvenergytotal":
        47728, "totworktime": 14793746, "epv1today": 222, "epv1total": 25999,
        "epv2today": 158, "epv2total": 18509, "epvtotal": 44508, "pvtemperature": 596,
        "pvipmtemperature": 332, "pvboottemperature": 311, "uwBatVolt_DSP": 0,
        "pbusvolt": 3464, "nbusvolt": 3482}}
- No MQTT message sent, MQTT disabled
- Grott Send data to PVOutput disabled
- Grott Send data to Influx disabled
- Grott extension processing started:  grotcsv
- Grott extension processing error: TypeError("'Conf' object does not support item assignment")
- Data less then minimum record length, data not processed
- Data less then minimum record length, data not processed

Any idea?

**Comment by Hemmahackaren** [comment]
Thanks, seems to work now :) Very fast!

I will test your fork more tomorrow, sun is fading and inverter shutting off soon

**Comment by rany2** [comment]
@Hemmahackaren please update to the latest version, I fixed another bug related to extensions which might impact grottcsv.

**Comment by Hemmahackaren** [comment]
@rany2 

I have run a while before updating, no issues - everything seems to work.

Then updated to latest version and it seems to work, but values in csv-file are now in decimal and not integers. One could argue that is more user friendly and a better way. But as my use of the csv-files expects it in old non decimal format it is an issue for me so I reverted back.

If decimals is the way to go forward I can change my routines.

CSV before latest version:
device,time,datalogserial,pvserial,pvstatus,pvpowerin,pv1voltage,pv1current,pv1watt,pv2voltage,pv2current,pv2watt,pvpowerout,pvfrequentie,pvgridvoltage,pvgridcurrent,pvgridpower,pvgridvoltage2,pvgridcurrent2,pvgridpower2,pvgridvoltage3,pvgridcurrent3,pvgridpower3,Vac_RS,Vac_ST,Vac_TR,pvenergytoday,pvenergytotal,totworktime,epv1today,epv1total,epv2today,epv2total,epvtotal,pvtemperature,pvipmtemperature,pvboottemperature,uwBatVolt_DSP,pbusvolt,nbusvolt
<snip>,2023-03-16T09:08:11,<snip>,<snip>,1,38309,6619,32,21180,5284,30,15852,37735,5001,2288,53,12126,2396,53,12698,2333,54,12598,3975,4136,4039,63,47793,14821890,34,26033,25,18534,44567,593,372,340,0,3377,3485
With latest version:
<snip>,2023-03-16T09:09:31,<snip>,<snip>,1,3750.5,658.8,3.1,2042.2,531.8,2.9,1542.2,3694.3,50.0,229.7,5.2,1194.4,239.1,5.2,1243.3,233.4,5.3,1237.0,398.0,413.6,404.4,6.4,4779.4,2058.62,3.4,2603.3,2.6,1853.5,4456.8,59.3,37.3,34.1,0.0,3362,3469
<snip>,2023-03-16T09:10:35,<snip>,<snip>,1,3693.9,662.8,3.1,2054.6,533.7,2.9,1547.7,3638.5,50.03,230.2,5.1,1174.0,237.0,5.1,1208.7,234.4,5.2,1218.8,397.4,412.7,404.9,6.5,4779.5,2058.64,3.4,2603.3,2.6,1853.5,4456.8,59.3,37.3,34.2,0.0,3381,3486

**Comment by rany2** [comment]
Hi, decimals are the way to go. The CSV was showing integers because it wasn't aware of the layout but fortunately this should be fixed now.
