### ISSUE TITLE
[GrottServer] Forwarding stops working after some time

### ISSUE THREAD

**Issue by rany2** [rany2/grott#48]
@vitj99 Could you please try the latest version? I've made changes to improve reliability of forwarding.

**Comment by vitj99** [comment]
@rany2 I use new files and all communication to growatt server was stopped. MQTT data are sometime lost. I tried also proxy mode and with this mode is everything OK.

**Comment by rany2** [comment]
> After some time was communication to growatt server restored. I will see more at morning.

So currently GrottServer is working OK but needs more testing to confirm?
