### ISSUE TITLE
Increasing interval in proxy mode

### ISSUE THREAD

**Issue by hugoboss00** [rany2/grott#9]
Hi,
Currently when using a datalogger interval < 1min in proxy mode the datalogger starts to behave abnormal (i.e. sending the same msg again, see also https://github.com/johanmeijer/grott/discussions/93#discussioncomment-2167828 at johanns repo)
From the comments in this issue, it looks like the growatt server is here the bottleneck.
Do you think it would be possible to decouple somehow the forwarding interval to growatt server from the sending interval to mqtt/influx?
Then it would be possible to have i.e. 10s datalogger interval, but forwarded just every 5 mins to growatt servers.

I know that there is also the server mode in grott which should be able to handle 10s interval, but then i would loose the statistics on the growatt website. My usecase is having a mqtt LCD device hanging on the wall showing the current PV data as fast as possible and using the growatt website for long term statistics.

**Comment by rany2** [comment]
My fork of grott has a serverforward mode so that you could use server mode while keeping forwarding to growatt's website for long term statistics.

You need something like this in grott.ini:

```
[Server]
serverforward = True
```

**Comment by hugoboss00** [comment]
yes, that worked.
thanks
